### ISSUE TITLE
Support for orange pi (allwinner h3, h5, h6 based) board

### ISSUE THREAD

**Issue by trogalko** [seeul8er/DroneBridge#11]
Hi, could You add these boards to run DroneBridge?
Is there such as custom install script rather than board-specific-ready-to-use-image?
that would be great addition.
Thank You

**Comment by seeul8er** [comment]
Hi,
that pops up in the EZ-WifiBroadcast thread from time to time. 
Unfortunately, no. The images come with a custom kernel and drivers, so a simple install script will not do.
Porting DroneBridge to Orange Pi would be possible I think. But the question is: Would it be worth it? As far as I know the camera of the Pi is superior to the stuff available for Orange Pi. Also capture latency is a big thing. That is very much optimized for the Orange Pi. Forget USB webcams etc.
So in order to get it running properly I you would need to invest a lot of time... The Pi3 is more than capable to run everything, cheaper and more popular. I do not see the benefit.

If you decide to give it a try I will see if I can help you out with question. But right now my focus is on other things. The system still is buggy.
