### ISSUE TITLE
Differences between DroneBridge-raw-protocol and DroneBridge-RC-packet

### ISSUE THREAD

**Issue by ewized** [seeul8er/DroneBridge#23]
Currently looking into this and want to know the differences between the two. Also if the RC packet is better is there a way to send this packet via a python lib script, also to have it received from the uav via python lib as well.

**Comment by seeul8er** [comment]
The RC packet is embedded into the raw protocol. It is the payload.
The raw protocol is the very basis of all long-range communication. The RC packet is better than sending MAVLink or MSP packets (embedded into the raw protocol) over the long-range link since they have some overhead. RC packets are more efficient.
So a RC-message would look something like this:

`<rawprotocol_header><RC-packet>`

Because of that, you can send/receive RC packets using the python lib (python lib only does raw protocol). However, you need to implement the RC packet yourself. There currently is no python implementation for creating RC-packets.
