### ISSUE TITLE
Video Glitch

### ISSUE THREAD

**Issue by JRicardoPC** [seeul8er/DroneBridge#33]
Hello,
I have a trouble with dronebridge v0.5 and 0.6. The video in the ground station have glitch all the time.
With the V0.3 or v0.4 i don’t have any problem with this.

Hardware
UAV: Raspberry Pi zero and Tp-link TL-WN722N
Ground: Raspberry Pi3 and Tp-link TL-WN722N

**Comment by seeul8er** [comment]
Thanks for testing it :) 
I can assure you that I did not change anything from v0.3 to v0.4 to v0.5 that is/was part of the video pipeline. So all the firmware, drivers and programmes are exactly the same (WBC code) in all of the three images.

Since I got no clue what could cause your problems I will close this issue for now. If more people complain about the same thing I might reopen this one.
Sorry I can not help you. The link quality is highly dependent on the environment so maybe some nearby devices like WiFi APs cause problems.
