### ISSUE TITLE
Comparison between projects

### ISSUE THREAD

**Issue by Summer88** [seeul8er/DroneBridge#44]
Dear Sirs,
I'm looking around for a way to transmit both video and RC Mavlink data over 2.4 Ghz, found many projects about this but cannot get a starting point:

From this document https://dronebridge.gitbook.io/docs/comparison they put comparison on:

svpcoms WifiBroadcast (basic TX-RX)
DroneBridge (system design with library)
OpenHD (follow-up on EZ-WifiBroadcast)
EZ-Wifibroadcast (not under development)

But looking at code the most updated seems that svpcoms WifiBroadcast and is able to manage both video and Mavlink.

Dronebridge is still developed?

**Comment by seeul8er** [comment]
All of them can do MAVLink telemetry. MAVLink RC is currently limited to 8 channels as far as I kno. With DroneBridge you could also easily write your own python script to read & transmit the data using the library. But nothing wrong with using svpcoms implementation.

DroneBridge is under active development, but not as intense at the moment since I got other things on my plate as well.
